networks:
  default:
    external:
      name: roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  # docker run -d --name mongodb --network=roboshop mongodb:v1
  mongodb:
    image: joindevops/mongodb:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume
    # networks:
    # - roboshop

  catalogue:
    image: joindevops/catalogue:v1
    container_name: catalogue
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web:
    image: joindevops/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment

  redis:
    image: redis
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  user:
    image: joindevops/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: joindevops/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue

  mysql:
    image: joindevops/mysql:v1
    container_name: mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  shipping:
    image: joindevops/shipping:v1
    container_name: shipping
    depends_on:
    - mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
    - source: mysql
      target: /var/lib/rabbitmq
      type: volume

  payment:
    container_name: payment
    image: joindevops/payment:v1
    depends_on:
    - rabbitmq
    - user
    - cart

